export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'api',
        'admin-portal',
        'teacher-portal',
        'parent-portal',
        'student-portal',
        'parent-mobile',
        'teacher-mobile',
        'operator-console',
        'shared',
        'domain',
        'ui',
        'i18n',
        'api-client',
        'logging',
        'config',
        'notification-worker',
        'report-worker',
        'observability',
        'eslint-config',
        'typescript-config',
        'jest-config',
        'ci',
        'deps',
        'docs',
        'infra',
        'repo',
      ],
    ],
    'subject-case': [2, 'always', ['sentence-case', 'lower-case']],
  },
};
